### ISSUE TITLE
feign doesn't support request body?

### ISSUE THREAD

**Issue by haroldjiang** [kbastani/spring-cloud-microservice-example#12] opened 2015-11-21 00:16 UTC
thanks for you demo code ,it helped me a lot.still got some trouble here.
Below is some code snippet in SpringMvcContract.java
 in this method:
 protected boolean processAnnotationsOnParameter(MethodMetadata data, Annotation[] annotations, int paramIndex) {
 there is the code:
 AnnotatedParameterProcessor processor =
 annotatedArgumentProcessors.get(parameterAnnotation.annotationType());
 isHttpAnnotation |= processor.processArgument(context, parameterAnnotation);

the movie ui service has a userClient annotated with  @FeignClient and there is a method "void createUser(@RequestBody User user);"

 annotatedArgumentProcessors will get a null processor because of annotatedArgumentProcessors get initialized by getDefaultAnnotatedArgumentsProcessors which only used three defautlt processors by PathVariableParameterProcessor,RequestParamParameterProcessor,RequestHeaderParameterProcessor.

and the result is it will throw nullpointer exception.
 is this a bug or just something i forget to config.

@kbastani

**Comment by kbastani** [comment] 2015-12-07 19:56
Please provide details of the exception

**Comment by kbastani** [comment] 2015-12-09 06:34
Closing the issue. Please either re-open the issue if the problem is still relevant or create a Stackoverflow question with a Spring Cloud tag.

**Closed by kbastani** 2015-12-09 06:34 UTC
