### ISSUE TITLE
Broken dep

### ISSUE THREAD

**Issue by unitymind** [kbastani/spring-cloud-microservice-example#1] opened 2015-07-14 00:44 UTC
```[ERROR] Failed to execute goal on project users-microservice: Could not resolve dependencies for project org.kbastani:users-microservice:jar:0.1.0: Could not find artifact org.springframework.data:spring-data-neo4j:jar:3.4.0.BUILD-SNAPSHOT in spring-snapshots (http://repo.spring.io/libs-snapshot-local) -> [Help 1]```

No thoughts why (

**Comment by kbastani** [comment] 2015-07-15 00:33
This looks like a duplicate of https://github.com/kbastani/spring-cloud-microservice-example/pull/2

**Closed by kbastani** 2015-07-15 00:33 UTC
